updated npol_to_mzp transformation by inverting Eq 44
punch-mission/solpolpy pull request #158
Opened 2024-09-05 22:23 UTC by s0larish

## PR summary

*What does this PR introduce?*

[ ] Modifies npol_to_mzp in transforms.py by inverting Eq 44 in DeForest et al (2022)

2024-09-09 14:02 UTC, jmbhughes requested changes
See my comments please. Overall, can you describe why this is an improvement over the existing function?

2024-09-09 14:02 UTC, jmbhughes commented on solpolpy/transforms.py
> +            raise ValueError("Conversion matrix is degenerate")
Can we make this a custom error?

2024-09-09 14:02 UTC, jmbhughes commented on solpolpy/transforms.py
> +    phi = [input_collection[key].meta['POLAR'] for key in input_keys if key != 'alpha']*u.degree
I know phi comes from the paper, but it's a bit of an opaque name.

2024-09-09 14:02 UTC, jmbhughes commented on solpolpy/transforms.py
> +    Bmzp_cube = [(key, NDCube(data_mzp_solar[:, :, i, 0], wcs=input_collection[input_keys[0]].wcs,
I don't really like calling this a cube. It's a list of cubes.

2024-09-09 21:07 UTC, s0larish commented on solpolpy/transforms.py
> +            raise
If the conversion matrix turns out to be singular and inversion could not be done

2024-09-10 16:13 UTC, jmbhughes commented on solpolpy/transforms.py
> +            raise
Yes. But you just have `else: raise` without anything actually being raised.

2024-10-04 17:28 UTC, s0larish commented on solpolpy/transforms.py
> +            raise
removed the else condition in the new push

2024-11-02 21:50 UTC, merged